import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gear Up',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className='relative h-full w-full overflow-hidden '>
      <body className={`${inter.className} bg-white bg-no-repeat h-full w-screen `}>
        {children}
        <Navbar userSlug={session?.user?.slug} userRole={session?.user?.userRole}/>
      </body>
    </html>
  )
}
